#pragma once

#include <cstdint>

// Procedural box drawing / block element table.
// 160 entries covering U+2500–U+259F, indexed by (codepoint - 0x2500).
// Each uint32_t encodes the geometry for one character.
//
// Encoding:
//   bits 0-2:   type (0=none, 1=rect, 2=quadrant, 3=shade, 4=box_line)
//
//   type 1 (rect): axis-aligned rectangle in cell-eighths
//     bits 3-6:   x0 (0-8)
//     bits 7-10:  x1 (0-8)
//     bits 11-14: y0 (0-8)
//     bits 15-18: y1 (0-8)
//
//   type 2 (quadrant): combination of quarter-cell fills
//     bits 3-6:   mask (bit0=UL, bit1=UR, bit2=LL, bit3=LR)
//
//   type 3 (shade): uniform fill at fractional density
//     bits 3-4:   level (1=light/25%, 2=medium/50%, 3=dark/75%)
//
//   type 4 (box drawing line): centered lines connecting edges
//     bits 3-4:   left  (0=none, 1=light, 2=heavy, 3=double)
//     bits 5-6:   right (0=none, 1=light, 2=heavy, 3=double)
//     bits 7-8:   up    (0=none, 1=light, 2=heavy, 3=double)
//     bits 9-10:  down  (0=none, 1=light, 2=heavy, 3=double)
//     bits 11-14: style (0=solid, 1=dash2, 2=dash3, 3=dash4, 4=round_corner, 5=diagonal)

namespace BoxDrawing {

// Helper macros for building table entries
#define BD_NONE  0u
#define BD_RECT(x0, x1, y0, y1)  (1u | ((x0)<<3) | ((x1)<<7) | ((y0)<<11) | ((y1)<<15))
#define BD_QUAD(mask)             (2u | ((mask)<<3))
#define BD_SHADE(level)           (3u | ((level)<<3))
#define BD_LINE(l, r, u, d)      (4u | ((l)<<3) | ((r)<<5) | ((u)<<7) | ((d)<<9))
#define BD_LINED(l, r, u, d, s)  (4u | ((l)<<3) | ((r)<<5) | ((u)<<7) | ((d)<<9) | ((s)<<11))

// Line weights
#define L 1u  // light
#define H 2u  // heavy
#define D 3u  // double

// Dash styles
#define DASH2 1u
#define DASH3 2u
#define DASH4 3u
#define ROUND 4u
#define DIAG  5u

inline constexpr uint32_t kTableSize = 160; // 0x259F - 0x2500 + 1
inline constexpr uint32_t kBaseCodepoint = 0x2500;

// Table indexed by (codepoint - 0x2500)
inline constexpr uint32_t kTable[kTableSize] = {
    // === Box Drawing Characters (U+2500–U+257F) ===

    // U+2500  ─  BOX DRAWINGS LIGHT HORIZONTAL
    BD_LINE(L, L, 0, 0),
    // U+2501  ━  BOX DRAWINGS HEAVY HORIZONTAL
    BD_LINE(H, H, 0, 0),
    // U+2502  │  BOX DRAWINGS LIGHT VERTICAL
    BD_LINE(0, 0, L, L),
    // U+2503  ┃  BOX DRAWINGS HEAVY VERTICAL
    BD_LINE(0, 0, H, H),

    // U+2504  ┄  BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
    BD_LINED(L, L, 0, 0, DASH3),
    // U+2505  ┅  BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
    BD_LINED(H, H, 0, 0, DASH3),
    // U+2506  ┆  BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
    BD_LINED(0, 0, L, L, DASH3),
    // U+2507  ┇  BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
    BD_LINED(0, 0, H, H, DASH3),

    // U+2508  ┈  BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
    BD_LINED(L, L, 0, 0, DASH4),
    // U+2509  ┉  BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
    BD_LINED(H, H, 0, 0, DASH4),
    // U+250A  ┊  BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
    BD_LINED(0, 0, L, L, DASH4),
    // U+250B  ┋  BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
    BD_LINED(0, 0, H, H, DASH4),

    // U+250C  ┌  BOX DRAWINGS LIGHT DOWN AND RIGHT
    BD_LINE(0, L, 0, L),
    // U+250D  ┍  BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
    BD_LINE(0, H, 0, L),
    // U+250E  ┎  BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
    BD_LINE(0, L, 0, H),
    // U+250F  ┏  BOX DRAWINGS HEAVY DOWN AND RIGHT
    BD_LINE(0, H, 0, H),

    // U+2510  ┐  BOX DRAWINGS LIGHT DOWN AND LEFT
    BD_LINE(L, 0, 0, L),
    // U+2511  ┑  BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
    BD_LINE(H, 0, 0, L),
    // U+2512  ┒  BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
    BD_LINE(L, 0, 0, H),
    // U+2513  ┓  BOX DRAWINGS HEAVY DOWN AND LEFT
    BD_LINE(H, 0, 0, H),

    // U+2514  └  BOX DRAWINGS LIGHT UP AND RIGHT
    BD_LINE(0, L, L, 0),
    // U+2515  ┕  BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
    BD_LINE(0, H, L, 0),
    // U+2516  ┖  BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
    BD_LINE(0, L, H, 0),
    // U+2517  ┗  BOX DRAWINGS HEAVY UP AND RIGHT
    BD_LINE(0, H, H, 0),

    // U+2518  ┘  BOX DRAWINGS LIGHT UP AND LEFT
    BD_LINE(L, 0, L, 0),
    // U+2519  ┙  BOX DRAWINGS UP LIGHT AND LEFT HEAVY
    BD_LINE(H, 0, L, 0),
    // U+251A  ┚  BOX DRAWINGS UP HEAVY AND LEFT LIGHT
    BD_LINE(L, 0, H, 0),
    // U+251B  ┛  BOX DRAWINGS HEAVY UP AND LEFT
    BD_LINE(H, 0, H, 0),

    // U+251C  ├  BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    BD_LINE(0, L, L, L),
    // U+251D  ┝  BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
    BD_LINE(0, H, L, L),
    // U+251E  ┞  BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT
    BD_LINE(0, L, H, L),
    // U+251F  ┟  BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT
    BD_LINE(0, L, L, H),

    // U+2520  ┠  BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
    BD_LINE(0, L, H, H),
    // U+2521  ┡  BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY
    BD_LINE(0, H, H, L),
    // U+2522  ┢  BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY
    BD_LINE(0, H, L, H),
    // U+2523  ┣  BOX DRAWINGS HEAVY VERTICAL AND RIGHT
    BD_LINE(0, H, H, H),

    // U+2524  ┤  BOX DRAWINGS LIGHT VERTICAL AND LEFT
    BD_LINE(L, 0, L, L),
    // U+2525  ┥  BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
    BD_LINE(H, 0, L, L),
    // U+2526  ┦  BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT
    BD_LINE(L, 0, H, L),
    // U+2527  ┧  BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT
    BD_LINE(L, 0, L, H),

    // U+2528  ┨  BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
    BD_LINE(L, 0, H, H),
    // U+2529  ┩  BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY
    BD_LINE(H, 0, H, L),
    // U+252A  ┪  BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY
    BD_LINE(H, 0, L, H),
    // U+252B  ┫  BOX DRAWINGS HEAVY VERTICAL AND LEFT
    BD_LINE(H, 0, H, H),

    // U+252C  ┬  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    BD_LINE(L, L, 0, L),
    // U+252D  ┭  BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT
    BD_LINE(H, L, 0, L),
    // U+252E  ┮  BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT
    BD_LINE(L, H, 0, L),
    // U+252F  ┯  BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY
    BD_LINE(H, H, 0, L),

    // U+2530  ┰  BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
    BD_LINE(L, L, 0, H),
    // U+2531  ┱  BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY
    BD_LINE(H, L, 0, H),
    // U+2532  ┲  BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY
    BD_LINE(L, H, 0, H),
    // U+2533  ┳  BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
    BD_LINE(H, H, 0, H),

    // U+2534  ┴  BOX DRAWINGS LIGHT UP AND HORIZONTAL
    BD_LINE(L, L, L, 0),
    // U+2535  ┵  BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT
    BD_LINE(H, L, L, 0),
    // U+2536  ┶  BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT
    BD_LINE(L, H, L, 0),
    // U+2537  ┷  BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
    BD_LINE(H, H, L, 0),

    // U+2538  ┸  BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
    BD_LINE(L, L, H, 0),
    // U+2539  ┹  BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY
    BD_LINE(H, L, H, 0),
    // U+253A  ┺  BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY
    BD_LINE(L, H, H, 0),
    // U+253B  ┻  BOX DRAWINGS HEAVY UP AND HORIZONTAL
    BD_LINE(H, H, H, 0),

    // U+253C  ┼  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    BD_LINE(L, L, L, L),
    // U+253D  ┽  BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT
    BD_LINE(H, L, L, L),
    // U+253E  ┾  BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT
    BD_LINE(L, H, L, L),
    // U+253F  ┿  BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY
    BD_LINE(H, H, L, L),

    // U+2540  ╀  BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT
    BD_LINE(L, L, H, L),
    // U+2541  ╁  BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT
    BD_LINE(L, L, L, H),
    // U+2542  ╂  BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
    BD_LINE(L, L, H, H),
    // U+2543  ╃  BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT
    BD_LINE(H, L, H, L),

    // U+2544  ╄  BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT
    BD_LINE(L, H, H, L),
    // U+2545  ╅  BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT
    BD_LINE(H, L, L, H),
    // U+2546  ╆  BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT
    BD_LINE(L, H, L, H),
    // U+2547  ╇  BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY
    BD_LINE(H, H, H, L),

    // U+2548  ╈  BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY
    BD_LINE(H, H, L, H),
    // U+2549  ╉  BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY
    BD_LINE(H, L, H, H),
    // U+254A  ╊  BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY
    BD_LINE(L, H, H, H),
    // U+254B  ╋  BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
    BD_LINE(H, H, H, H),

    // U+254C  ╌  BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL
    BD_LINED(L, L, 0, 0, DASH2),
    // U+254D  ╍  BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL
    BD_LINED(H, H, 0, 0, DASH2),
    // U+254E  ╎  BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL
    BD_LINED(0, 0, L, L, DASH2),
    // U+254F  ╏  BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL
    BD_LINED(0, 0, H, H, DASH2),

    // U+2550  ═  BOX DRAWINGS DOUBLE HORIZONTAL
    BD_LINE(D, D, 0, 0),
    // U+2551  ║  BOX DRAWINGS DOUBLE VERTICAL
    BD_LINE(0, 0, D, D),

    // U+2552  ╒  BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
    BD_LINE(0, D, 0, L),
    // U+2553  ╓  BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
    BD_LINE(0, L, 0, D),
    // U+2554  ╔  BOX DRAWINGS DOUBLE DOWN AND RIGHT
    BD_LINE(0, D, 0, D),

    // U+2555  ╕  BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
    BD_LINE(D, 0, 0, L),
    // U+2556  ╖  BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
    BD_LINE(L, 0, 0, D),
    // U+2557  ╗  BOX DRAWINGS DOUBLE DOWN AND LEFT
    BD_LINE(D, 0, 0, D),

    // U+2558  ╘  BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
    BD_LINE(0, D, L, 0),
    // U+2559  ╙  BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
    BD_LINE(0, L, D, 0),
    // U+255A  ╚  BOX DRAWINGS DOUBLE UP AND RIGHT
    BD_LINE(0, D, D, 0),

    // U+255B  ╛  BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
    BD_LINE(D, 0, L, 0),
    // U+255C  ╜  BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
    BD_LINE(L, 0, D, 0),
    // U+255D  ╝  BOX DRAWINGS DOUBLE UP AND LEFT
    BD_LINE(D, 0, D, 0),

    // U+255E  ╞  BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
    BD_LINE(0, D, L, L),
    // U+255F  ╟  BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
    BD_LINE(0, L, D, D),

    // U+2560  ╠  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    BD_LINE(0, D, D, D),
    // U+2561  ╡  BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
    BD_LINE(D, 0, L, L),
    // U+2562  ╢  BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
    BD_LINE(L, 0, D, D),
    // U+2563  ╣  BOX DRAWINGS DOUBLE VERTICAL AND LEFT
    BD_LINE(D, 0, D, D),

    // U+2564  ╤  BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
    BD_LINE(D, D, 0, L),
    // U+2565  ╥  BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
    BD_LINE(L, L, 0, D),
    // U+2566  ╦  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    BD_LINE(D, D, 0, D),

    // U+2567  ╧  BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
    BD_LINE(D, D, L, 0),
    // U+2568  ╨  BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
    BD_LINE(L, L, D, 0),
    // U+2569  ╩  BOX DRAWINGS DOUBLE UP AND HORIZONTAL
    BD_LINE(D, D, D, 0),

    // U+256A  ╪  BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
    BD_LINE(D, D, L, L),
    // U+256B  ╫  BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
    BD_LINE(L, L, D, D),
    // U+256C  ╬  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
    BD_LINE(D, D, D, D),

    // U+256D  ╭  BOX DRAWINGS LIGHT ARC DOWN AND RIGHT
    BD_LINED(0, L, 0, L, ROUND),
    // U+256E  ╮  BOX DRAWINGS LIGHT ARC DOWN AND LEFT
    BD_LINED(L, 0, 0, L, ROUND),
    // U+256F  ╯  BOX DRAWINGS LIGHT ARC UP AND LEFT
    BD_LINED(L, 0, L, 0, ROUND),
    // U+2570  ╰  BOX DRAWINGS LIGHT ARC UP AND RIGHT
    BD_LINED(0, L, L, 0, ROUND),

    // U+2571  ╱  BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
    BD_LINED(0, 0, 0, 0, DIAG),  // special: forward diagonal
    // U+2572  ╲  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
    BD_LINED(0, 0, 0, 0, DIAG),  // special: back diagonal
    // U+2573  ╳  BOX DRAWINGS LIGHT DIAGONAL CROSS
    BD_LINED(0, 0, 0, 0, DIAG),  // special: both diagonals

    // U+2574  ╴  BOX DRAWINGS LIGHT LEFT
    BD_LINE(L, 0, 0, 0),
    // U+2575  ╵  BOX DRAWINGS LIGHT UP
    BD_LINE(0, 0, L, 0),
    // U+2576  ╶  BOX DRAWINGS LIGHT RIGHT
    BD_LINE(0, L, 0, 0),
    // U+2577  ╷  BOX DRAWINGS LIGHT DOWN
    BD_LINE(0, 0, 0, L),

    // U+2578  ╸  BOX DRAWINGS HEAVY LEFT
    BD_LINE(H, 0, 0, 0),
    // U+2579  ╹  BOX DRAWINGS HEAVY UP
    BD_LINE(0, 0, H, 0),
    // U+257A  ╺  BOX DRAWINGS HEAVY RIGHT
    BD_LINE(0, H, 0, 0),
    // U+257B  ╻  BOX DRAWINGS HEAVY DOWN
    BD_LINE(0, 0, 0, H),

    // U+257C  ╼  BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT
    BD_LINE(L, H, 0, 0),
    // U+257D  ╽  BOX DRAWINGS LIGHT UP AND HEAVY DOWN
    BD_LINE(0, 0, L, H),
    // U+257E  ╾  BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT
    BD_LINE(H, L, 0, 0),
    // U+257F  ╿  BOX DRAWINGS HEAVY UP AND LIGHT DOWN
    BD_LINE(0, 0, H, L),

    // === Block Elements (U+2580–U+259F) ===

    // U+2580  ▀  UPPER HALF BLOCK
    BD_RECT(0, 8, 0, 4),
    // U+2581  ▁  LOWER ONE EIGHTH BLOCK
    BD_RECT(0, 8, 7, 8),
    // U+2582  ▂  LOWER ONE QUARTER BLOCK
    BD_RECT(0, 8, 6, 8),
    // U+2583  ▃  LOWER THREE EIGHTHS BLOCK
    BD_RECT(0, 8, 5, 8),
    // U+2584  ▄  LOWER HALF BLOCK
    BD_RECT(0, 8, 4, 8),
    // U+2585  ▅  LOWER FIVE EIGHTHS BLOCK
    BD_RECT(0, 8, 3, 8),
    // U+2586  ▆  LOWER THREE QUARTERS BLOCK
    BD_RECT(0, 8, 2, 8),
    // U+2587  ▇  LOWER SEVEN EIGHTHS BLOCK
    BD_RECT(0, 8, 1, 8),
    // U+2588  █  FULL BLOCK
    BD_RECT(0, 8, 0, 8),
    // U+2589  ▉  LEFT SEVEN EIGHTHS BLOCK
    BD_RECT(0, 7, 0, 8),
    // U+258A  ▊  LEFT THREE QUARTERS BLOCK
    BD_RECT(0, 6, 0, 8),
    // U+258B  ▋  LEFT FIVE EIGHTHS BLOCK
    BD_RECT(0, 5, 0, 8),
    // U+258C  ▌  LEFT HALF BLOCK
    BD_RECT(0, 4, 0, 8),
    // U+258D  ▍  LEFT THREE EIGHTHS BLOCK
    BD_RECT(0, 3, 0, 8),
    // U+258E  ▎  LEFT ONE QUARTER BLOCK
    BD_RECT(0, 2, 0, 8),
    // U+258F  ▏  LEFT ONE EIGHTH BLOCK
    BD_RECT(0, 1, 0, 8),

    // U+2590  ▐  RIGHT HALF BLOCK
    BD_RECT(4, 8, 0, 8),
    // U+2591  ░  LIGHT SHADE
    BD_SHADE(1),
    // U+2592  ▒  MEDIUM SHADE
    BD_SHADE(2),
    // U+2593  ▓  DARK SHADE
    BD_SHADE(3),
    // U+2594  ▔  UPPER ONE EIGHTH BLOCK
    BD_RECT(0, 8, 0, 1),
    // U+2595  ▕  RIGHT ONE EIGHTH BLOCK
    BD_RECT(7, 8, 0, 8),

    // U+2596  ▖  QUADRANT LOWER LEFT
    BD_QUAD(0x4),
    // U+2597  ▗  QUADRANT LOWER RIGHT
    BD_QUAD(0x8),
    // U+2598  ▘  QUADRANT UPPER LEFT
    BD_QUAD(0x1),
    // U+2599  ▙  QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT
    BD_QUAD(0xD),
    // U+259A  ▚  QUADRANT UPPER LEFT AND LOWER RIGHT
    BD_QUAD(0x9),
    // U+259B  ▛  QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT
    BD_QUAD(0x7),
    // U+259C  ▜  QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT
    BD_QUAD(0xB),
    // U+259D  ▝  QUADRANT UPPER RIGHT
    BD_QUAD(0x2),
    // U+259E  ▞  QUADRANT UPPER RIGHT AND LOWER LEFT
    BD_QUAD(0x6),
    // U+259F  ▟  QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT
    BD_QUAD(0xE),
};

#undef BD_NONE
#undef BD_RECT
#undef BD_QUAD
#undef BD_SHADE
#undef BD_LINE
#undef BD_LINED
#undef L
#undef H
#undef D
#undef DASH2
#undef DASH3
#undef DASH4
#undef ROUND
#undef DIAG

} // namespace BoxDrawing
