# Generate Version.h with the current git hash + dirty flag. Invoked via
# `cmake -P` from a build-time custom target. The content-aware write at
# the bottom only touches the file when the hash changed, so clean
# rebuilds don't recompile main.cpp and other Version.h consumers.
#
# Expected variables (passed via -D on the cmake command line):
#   OUTPUT_FILE  — absolute path to the Version.h to write
#   SOURCE_DIR   — repository root for the git invocation

find_package(Git QUIET)

set(GIT_HASH "unknown")
set(GIT_DIRTY "")

if(Git_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short=12 HEAD
        WORKING_DIRECTORY ${SOURCE_DIR}
        OUTPUT_VARIABLE _hash
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _hash_rc
    )
    if(_hash_rc EQUAL 0 AND _hash)
        set(GIT_HASH "${_hash}")

        # Only flag tracked-file modifications. `git status --porcelain`
        # also lists untracked files, which would falsely flip the hash to
        # `-dirty` for unrelated workspace junk (vcpkg binary caches,
        # editor backups, etc.). `diff-index --quiet` returns non-zero iff
        # a tracked file differs from HEAD, which is the actual definition
        # of "the build was made from modified source".
        execute_process(
            COMMAND ${GIT_EXECUTABLE} diff-index --quiet HEAD --
            WORKING_DIRECTORY ${SOURCE_DIR}
            RESULT_VARIABLE _diff_rc
            ERROR_QUIET
        )
        if(NOT _diff_rc EQUAL 0)
            set(GIT_DIRTY "-dirty")
        endif()
    endif()
endif()

set(_content
"// Generated by cmake/GenerateVersion.cmake. Do not edit.
#pragma once

namespace mb {

inline constexpr const char *kGitHash = \"${GIT_HASH}${GIT_DIRTY}\";
inline constexpr const char *kVersion = \"${GIT_HASH}${GIT_DIRTY}\";

} // namespace mb
")

set(_existing "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
    file(WRITE "${OUTPUT_FILE}" "${_content}")
endif()
