# Generate Version.h with the current git hash, dirty flag, and build date.
# Invoked via `cmake -P` from a build-time custom target so every build sees a
# fresh hash. Writes only when content changes so a clean tree → clean tree
# rebuild doesn't trigger a relink.
#
# Expected variables (passed via -D on the cmake command line):
#   OUTPUT_FILE  — absolute path to the Version.h to write
#   SOURCE_DIR   — repository root for the git invocation

find_package(Git QUIET)

set(GIT_HASH "unknown")
set(GIT_DIRTY "")

if(Git_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short=12 HEAD
        WORKING_DIRECTORY ${SOURCE_DIR}
        OUTPUT_VARIABLE _hash
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _hash_rc
    )
    if(_hash_rc EQUAL 0 AND _hash)
        set(GIT_HASH "${_hash}")

        # `--ignore-submodules=all` keeps build-generated files in submodules
        # (e.g. 3rdparty/libgrapheme/gen/*.h) from flipping the parent repo to
        # dirty. Submodule pointer bumps are committed changes and would be
        # reflected in the hash itself.
        execute_process(
            COMMAND ${GIT_EXECUTABLE} status --porcelain --ignore-submodules=all
            WORKING_DIRECTORY ${SOURCE_DIR}
            OUTPUT_VARIABLE _status
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(_status)
            set(GIT_DIRTY "-dirty")
        endif()
    endif()
endif()

string(TIMESTAMP BUILD_DATE "%Y-%m-%d %H:%M:%S UTC" UTC)

set(_content
"// Generated by cmake/GenerateVersion.cmake. Do not edit.
#pragma once

namespace mb {

inline constexpr const char *kGitHash    = \"${GIT_HASH}${GIT_DIRTY}\";
inline constexpr const char *kBuildDate  = \"${BUILD_DATE}\";
inline constexpr const char *kVersion    = \"${GIT_HASH}${GIT_DIRTY} (${BUILD_DATE})\";

} // namespace mb
")

set(_existing "")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
    file(WRITE "${OUTPUT_FILE}" "${_content}")
endif()
